import { CompetitionCode, StageSQL, TournamentPhase } from '../types'

export const LEAGUE_RANK_BONUS: Record<
  CompetitionCode,
  Record<number, number>
> = {
  [CompetitionCode.UCL]: {
    1: 6,
    2: 5.75,
    3: 5.5,
    4: 5.25,
    5: 5,
    6: 4.75,
    7: 4.5,
    8: 4.25,
    9: 4,
    10: 3.75,
    11: 3.5,
    12: 3.25,
    13: 3,
    14: 2.75,
    15: 2.5,
    16: 2.25,
    17: 2,
    18: 1.75,
    19: 1.5,
    20: 1.25,
    21: 1,
    22: 0.75,
    23: 0.5,
    24: 0.25,
  },
  [CompetitionCode.UEL]: {
    1: 6,
    2: 5.75,
    3: 5.5,
    4: 5.25,
    5: 5,
    6: 4.75,
    7: 4.5,
    8: 4.25,
    9: 4,
    10: 3.75,
    11: 3.5,
    12: 3.25,
    13: 3,
    14: 2.75,
    15: 2.5,
    16: 2.25,
    17: 2,
    18: 1.75,
    19: 1.5,
    20: 1.25,
    21: 1,
    22: 0.75,
    23: 0.5,
    24: 0.25,
  },
  [CompetitionCode.UECL]: {
    1: 4,
    2: 3.75,
    3: 3.5,
    4: 3.25,
    5: 3,
    6: 2.75,
    7: 2.5,
    8: 2.25,
    9: 2,
    10: 1.875,
    11: 1.75,
    12: 1.625,
    13: 1.5,
    14: 1.375,
    15: 1.25,
    16: 1.125,
    17: 1,
    18: 0.875,
    19: 0.75,
    20: 0.625,
    21: 0.5,
    22: 0.375,
    23: 0.25,
    24: 0.125,
  },
}

export const PARTICIPATION_BONUS = {
  [CompetitionCode.UCL]: {
    [StageSQL.QR1]: 0,
    [StageSQL.QR2]: 0,
    [StageSQL.QR3]: 0,
    [StageSQL.QPO]: 0,
    [StageSQL.LP]: 6,
    [StageSQL.KPO]: 0,
    [StageSQL.R16]: 1.5,
    [StageSQL.QF]: 1.5,
    [StageSQL.SF]: 1.5,
    [StageSQL.F]: 1.5,
  },
  [CompetitionCode.UEL]: {
    [StageSQL.QR1]: 0,
    [StageSQL.QR2]: 0,
    [StageSQL.QR3]: 0,
    [StageSQL.QPO]: 0,
    [StageSQL.LP]: 0,
    [StageSQL.KPO]: 0,
    [StageSQL.R16]: 1,
    [StageSQL.QF]: 1,
    [StageSQL.SF]: 1,
    [StageSQL.F]: 1,
  },
  [CompetitionCode.UECL]: {
    [StageSQL.QR1]: 0,
    [StageSQL.QR2]: 0,
    [StageSQL.QR3]: 0,
    [StageSQL.QPO]: 0,
    [StageSQL.LP]: 0,
    [StageSQL.KPO]: 0,
    [StageSQL.R16]: 0.5,
    [StageSQL.QF]: 0.5,
    [StageSQL.SF]: 0.5,
    [StageSQL.F]: 0.5,
  },
}

export const TEAM_POINTS = {
  matchWin: {
    [CompetitionCode.UCL]: {
      [StageSQL.QR1]: 0,
      [StageSQL.QR2]: 0,
      [StageSQL.QR3]: 0,
      [StageSQL.QPO]: 0,
      [StageSQL.LP]: 2,
      [StageSQL.KPO]: 0,
      [StageSQL.R16]: 2,
      [StageSQL.QF]: 2,
      [StageSQL.SF]: 2,
      [StageSQL.F]: 2,
    },
    [CompetitionCode.UEL]: {
      [StageSQL.QR1]: 0,
      [StageSQL.QR2]: 0,
      [StageSQL.QR3]: 0,
      [StageSQL.QPO]: 0,
      [StageSQL.LP]: 2,
      [StageSQL.KPO]: 0,
      [StageSQL.R16]: 2,
      [StageSQL.QF]: 2,
      [StageSQL.SF]: 2,
      [StageSQL.F]: 2,
    },
    [CompetitionCode.UECL]: {
      [StageSQL.QR1]: 0,
      [StageSQL.QR2]: 0,
      [StageSQL.QR3]: 0,
      [StageSQL.QPO]: 0,
      [StageSQL.LP]: 2,
      [StageSQL.KPO]: 0,
      [StageSQL.R16]: 2,
      [StageSQL.QF]: 2,
      [StageSQL.SF]: 2,
      [StageSQL.F]: 2,
    },
  },
  matchDraw: {
    [CompetitionCode.UCL]: {
      [StageSQL.QR1]: 0,
      [StageSQL.QR2]: 0,
      [StageSQL.QR3]: 0,
      [StageSQL.QPO]: 0,
      [StageSQL.LP]: 1,
      [StageSQL.KPO]: 0,
      [StageSQL.R16]: 1,
      [StageSQL.QF]: 1,
      [StageSQL.SF]: 1,
      [StageSQL.F]: 1,
    },
    [CompetitionCode.UEL]: {
      [StageSQL.QR1]: 0,
      [StageSQL.QR2]: 0,
      [StageSQL.QR3]: 0,
      [StageSQL.QPO]: 0,
      [StageSQL.LP]: 1,
      [StageSQL.KPO]: 0,
      [StageSQL.R16]: 1,
      [StageSQL.QF]: 1,
      [StageSQL.SF]: 1,
      [StageSQL.F]: 1,
    },
    [CompetitionCode.UECL]: {
      [StageSQL.QR1]: 0,
      [StageSQL.QR2]: 0,
      [StageSQL.QR3]: 0,
      [StageSQL.QPO]: 0,
      [StageSQL.LP]: 1,
      [StageSQL.KPO]: 0,
      [StageSQL.R16]: 1,
      [StageSQL.QF]: 1,
      [StageSQL.SF]: 1,
      [StageSQL.F]: 1,
    },
  },
  elimination: {
    [CompetitionCode.UECL]: {
      [StageSQL.QR1]: 1,
      [StageSQL.QR2]: 1.5,
      [StageSQL.QR3]: 2,
      [StageSQL.QPO]: 2.5,
      [StageSQL.LP]: 0,
      [StageSQL.KPO]: 0,
      [StageSQL.R16]: 0,
      [StageSQL.QF]: 0,
      [StageSQL.SF]: 0,
      [StageSQL.F]: 0,
    },
  },
  participation: PARTICIPATION_BONUS,
  participationMin: {
    [CompetitionCode.UEL]: {
      [StageSQL.LP]: 3,
    },
    [CompetitionCode.UECL]: {
      [StageSQL.LP]: 2.5,
    },
  },
  bonus: LEAGUE_RANK_BONUS,
}

export const ASSOCIATION_POINTS = {
  matchWin: {
    [CompetitionCode.UCL]: {
      [TournamentPhase.Qualifying]: 1,
      [TournamentPhase.League]: 2,
      [TournamentPhase.Knockout]: 2,
    },
    [CompetitionCode.UEL]: {
      [TournamentPhase.Qualifying]: 1,
      [TournamentPhase.League]: 2,
      [TournamentPhase.Knockout]: 2,
    },
    [CompetitionCode.UECL]: {
      [TournamentPhase.Qualifying]: 1,
      [TournamentPhase.League]: 2,
      [TournamentPhase.Knockout]: 2,
    },
  },
  matchDraw: {
    [CompetitionCode.UCL]: {
      [TournamentPhase.Qualifying]: 0.5,
      [TournamentPhase.League]: 1,
      [TournamentPhase.Knockout]: 1,
    },
    [CompetitionCode.UEL]: {
      [TournamentPhase.Qualifying]: 0.5,
      [TournamentPhase.League]: 1,
      [TournamentPhase.Knockout]: 1,
    },
    [CompetitionCode.UECL]: {
      [TournamentPhase.Qualifying]: 0.5,
      [TournamentPhase.League]: 1,
      [TournamentPhase.Knockout]: 1,
    },
  },
  participation: PARTICIPATION_BONUS,
  bonus: LEAGUE_RANK_BONUS,
}
